---
# tasks file for ansible-ssh

- name: Create ~/.ssh if directory does not exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: 0700

- name: generate SSH key
  openssh_keypair:
    state: present
    comment: "{{ ssh_comment }}"
    path: "{{ ssh_path }}"
  register: task_result
